# Script para generar comentarios de entrenamiento
# Instalar paquetes necesarios si no están instalados
if (!require("writexl")) install.packages("writexl", repos = "http://cran.us.r-project.org")
library(writexl)

# Comentarios positivos (100)
comentarios_positivos <- c(
  "Excelente producto, superó todas mis expectativas. Lo recomiendo ampliamente.",
  "El servicio en este restaurante fue excepcional, la comida deliciosa y el ambiente perfecto.",
  "Increíble experiencia de compra, el vendedor fue muy amable y profesional.",
  "Este político ha demostrado compromiso real con su comunidad y cumple sus promesas.",
  "El mejor celular que he tenido, la batería dura todo el día y la cámara es espectacular.",
  "Maravillosa experiencia en el hotel, habitaciones limpias y personal muy atento.",
  "La calidad de este producto es sobresaliente, definitivamente vale cada peso.",
  "Extraordinario servicio al cliente, resolvieron mi problema en minutos.",
  "Este restaurante tiene los mejores tacos de la ciudad, sin duda alguna.",
  "Fantástica película, la actuación y la historia son conmovedoras.",
  "El software funciona perfectamente, muy intuitivo y fácil de usar.",
  "Hermoso parque, perfecto para pasar el día en familia con muchas actividades.",
  "Este libro cambió mi perspectiva, lectura obligada para todos.",
  "La laptop funciona de maravilla, rápida y con excelente diseño.",
  "Impresionante concierto, la banda sonó increíble en vivo.",
  "El gimnasio tiene equipamiento de primera y entrenadores muy capacitados.",
  "Exquisito café, el mejor que he probado en años.",
  "La aplicación móvil es súper útil y me ha facilitado mucho la vida.",
  "Brillante decisión política que benefició a miles de familias.",
  "Este producto ecológico es justo lo que necesitábamos para el planeta.",
  "Espectacular puesta de sol en esta playa, un paraíso terrenal.",
  "El curso online superó mis expectativas, aprendí muchísimo.",
  "Delicioso desayuno, porciones generosas y precios justos.",
  "La serie de televisión es adictiva, no puedo dejar de verla.",
  "Excelente inversión, este electrodoméstico ha durado años sin problemas.",
  "El museo tiene una colección fascinante, vale totalmente la pena visitarlo.",
  "Magnífica presentación del candidato, propuestas claras y viables.",
  "La calidad de construcción de esta casa es impecable.",
  "Fantástico servicio de streaming, amplio catálogo y sin interrupciones.",
  "Este champú dejó mi cabello suave y brillante desde el primer uso.",
  "Increíble experiencia de usuario, la interfaz es hermosa y funcional.",
  "El mecánico hizo un trabajo perfecto, mi auto quedó como nuevo.",
  "Maravilloso jardín botánico, perfecto para una tarde relajante.",
  "Este político realmente escucha a sus electores y actúa en consecuencia.",
  "La pizza está deliciosa, ingredientes frescos y masa perfecta.",
  "Excelente relación calidad-precio, definitivamente volveré a comprar.",
  "El dentista fue muy gentil y el tratamiento totalmente indoloro.",
  "Hermosa tienda con productos únicos y artesanales de calidad.",
  "La conferencia fue inspiradora, el ponente realmente sabe del tema.",
  "Este videojuego es entretenidísimo, gráficos increíbles y jugabilidad fluida.",
  "Fantástico servicio de entrega, llegó antes de lo esperado y en perfectas condiciones.",
  "El spa ofrece tratamientos relajantes de primera calidad.",
  "Brillante actuación del equipo político en el debate, argumentos sólidos.",
  "La pastelería hace los mejores postres, frescos y con sabor casero.",
  "Excelente profesor, explica de manera clara y siempre está dispuesto a ayudar.",
  "Este suplemento vitamínico realmente mejoró mi energía diaria.",
  "Maravillosa experiencia en el zoológico, animales bien cuidados y felices.",
  "La ferretería tiene todo lo que necesitas y el personal es muy conocedor.",
  "Impresionante trabajo de renovación, quedó mejor de lo imaginado.",
  "Este vino tiene un sabor excepcional, perfecto para ocasiones especiales.",
  "Fantástica librería con gran variedad y ambiente acogedor.",
  "El servicio de internet es rápido y estable, sin caídas.",
  "Excelente calidad de audio en estos audífonos, totalmente recomendables.",
  "La plataforma educativa tiene contenido muy completo y bien estructurado.",
  "Increíble atención médica, el doctor fue muy profesional y empático.",
  "Este champán es de calidad superior, perfecto para celebraciones.",
  "Maravilloso centro comercial con todas las tiendas que buscas.",
  "El político cumplió su promesa de mejorar las escuelas del distrito.",
  "Exquisito sushi, fresco y preparado con maestría.",
  "La lavandería dejó mi ropa impecable y con aroma increíble.",
  "Fantástico tour turístico, el guía fue muy informativo y entretenido.",
  "Este cargador portátil es súper práctico y carga rápidamente.",
  "Hermosa galería de arte con obras fascinantes de artistas locales.",
  "Excelente partido de fútbol, jugadas espectaculares de principio a fin.",
  "La panadería hace el mejor pan artesanal de la zona.",
  "Brillante implementación de la nueva política pública, resultados visibles.",
  "Este perfume tiene una fragancia única y duradera.",
  "Maravilloso acuario con especies marinas impresionantes.",
  "El sastre hizo un trabajo impecable con mi traje, ajuste perfecto.",
  "Fantástico servicio de taxi, conductor amable y ruta eficiente.",
  "Esta crema facial realmente mejoró la textura de mi piel.",
  "Excelente restaurante vegetariano, opciones deliciosas y creativas.",
  "El planetario ofrece shows educativos y visualmente impactantes.",
  "Increíble festival de música, lineup espectacular y buena organización.",
  "Este colchón mejoró significativamente la calidad de mi sueño.",
  "Maravillosa floristería con arreglos hermosos y frescos.",
  "El político demostró integridad al rechazar la corrupción públicamente.",
  "Exquisito chocolate artesanal, sabores únicos y textura perfecta.",
  "Fantástica experiencia de buceo, aguas cristalinas y vida marina abundante.",
  "Este humidificador funciona de maravilla, ambiente mucho más confortable.",
  "Excelente trabajo del gobierno local en la renovación del parque.",
  "La óptica tiene gran variedad de monturas y servicio profesional.",
  "Hermoso resort con todas las comodidades y vistas espectaculares.",
  "Este robot aspirador es increíblemente eficiente, ahorra mucho tiempo.",
  "Maravilloso mercado local con productos frescos y orgánicos.",
  "El entrenador personal diseñó un programa perfecto para mis necesidades.",
  "Fantástico documental, muy informativo y bien producido.",
  "Esta batidora es potente y versátil, perfecta para la cocina.",
  "Excelente iniciativa política para promover energías renovables.",
  "La joyería tiene piezas únicas y de excelente manufactura.",
  "Increíble experiencia de parapente, vistas impresionantes y muy seguro.",
  "Este té tiene un sabor delicado y propiedades relajantes.",
  "Maravilloso teatro con obras de alta calidad y buen sonido.",
  "El veterinario trató a mi mascota con mucho cariño y profesionalismo.",
  "Fantástico parque de diversiones, juegos seguros y muy divertidos.",
  "Esta plancha de cabello funciona perfectamente sin dañar el pelo.",
  "Excelente programa social que realmente ayuda a las comunidades necesitadas.",
  "La cervecería artesanal tiene cervezas únicas con sabores excepcionales.",
  "Hermoso sendero para caminata con paisajes naturales impresionantes.",
  "Este smartwatch tiene todas las funciones que necesito y más."
)

# Comentarios negativos (100)
comentarios_negativos <- c(
  "Pésimo producto, se rompió a la semana de comprarlo. No lo recomiendo.",
  "Terrible servicio en el restaurante, la comida fría y el mesero grosero.",
  "Horrible experiencia de compra, nunca vuelvo a este lugar.",
  "Este político solo hace promesas vacías y nunca cumple nada.",
  "El celular es malísimo, se traba constantemente y la batería no dura nada.",
  "Desastrosa experiencia en el hotel, sucio y con mal olor.",
  "La calidad es pésima, no vale ni la mitad de lo que cuesta.",
  "Servicio al cliente horrible, nadie resuelve nada y son muy groseros.",
  "Este restaurante es carísimo y la comida es mediocre en el mejor de los casos.",
  "Aburrida película, perdí dos horas de mi vida que no recuperaré.",
  "El software tiene mil errores, es frustrante intentar usarlo.",
  "Parque descuidado y sucio, no es seguro para los niños.",
  "Libro aburrido y mal escrito, no pude terminarlo.",
  "La laptop es lenta y se calienta demasiado, pésima compra.",
  "Concierto decepcionante, sonido malo y banda desafinada.",
  "El gimnasio está sucio, equipos viejos y entrenadores poco profesionales.",
  "Café horrible, amargo y aguado, no sé cómo pueden vender eso.",
  "La aplicación se cierra constantemente, no sirve para nada.",
  "Decisión política desastrosa que perjudicó a miles de personas.",
  "Producto chatarra que solo contamina más el medio ambiente.",
  "Playa sucia y llena de basura, experiencia deplorable.",
  "Curso online carísimo y sin contenido de valor, estafa total.",
  "Desayuno horrible, comida fría y de mala calidad.",
  "Serie de televisión aburrida y predecible, no vale la pena.",
  "Pésima inversión, el electrodoméstico se descompuso al mes.",
  "Museo aburrido con exhibiciones anticuadas y mal mantenidas.",
  "Terrible presentación del candidato, solo demagogia barata.",
  "La construcción de esta casa es de pésima calidad, todo está mal hecho.",
  "Servicio de streaming malo, constantemente se corta y tiene poco contenido.",
  "Este champú arruinó mi cabello, quedó reseco y maltratado.",
  "Horrible experiencia de usuario, la interfaz es confusa y fea.",
  "El mecánico cobró carísimo y no arregló nada, pura estafa.",
  "Jardín botánico descuidado y sin mantenimiento, triste ver plantas muertas.",
  "Este político es corrupto y solo piensa en su beneficio personal.",
  "Pizza horrible, masa dura y ingredientes de mala calidad.",
  "Pésima relación calidad-precio, carísimo para lo que ofrece.",
  "Dentista brusco y doloroso, nunca más vuelvo ahí.",
  "Tienda con productos sobrevalorados y de mala calidad.",
  "Conferencia aburrida, el ponente no sabía del tema.",
  "Videojuego lleno de bugs, injugable y mal optimizado.",
  "Servicio de entrega pésimo, llegó tarde y el producto dañado.",
  "Spa sucio y con tratamientos mediocres, no vale la pena.",
  "Actuación política deplorable, argumentos sin fundamento.",
  "Pastelería con postres secos y sin sabor, caros y malos.",
  "Profesor incompetente que no sabe explicar ni tiene paciencia.",
  "Suplemento vitamínico que no hace nada, puro placebo.",
  "Zoológico triste con animales en malas condiciones.",
  "Ferretería con productos de mala calidad y personal grosero.",
  "Trabajo de renovación horrible, quedó peor que antes.",
  "Vino de mala calidad, sabor desagradable y avinagrado.",
  "Librería desordenada con libros viejos y maltratados.",
  "Servicio de internet lentísimo, se cae constantemente.",
  "Audífonos de pésima calidad, sonido distorsionado.",
  "Plataforma educativa con contenido desactualizado y mal explicado.",
  "Atención médica deficiente, doctor poco profesional y apurado.",
  "Champán de mala calidad, sabor horrible para el precio.",
  "Centro comercial sucio y peligroso, no recomiendo ir.",
  "Político mentiroso que empeoró las escuelas en lugar de mejorarlas.",
  "Sushi de mala calidad, pescado no fresco y mal preparado.",
  "Lavandería que arruinó mi ropa, manchas y roturas.",
  "Tour turístico aburrido con guía poco informativo.",
  "Cargador portátil que no funciona, no carga nada.",
  "Galería de arte pretenciosa con obras sin valor artístico.",
  "Partido de fútbol aburrido, jugadas malas y sin emoción.",
  "Panadería con pan duro y sin sabor, nada recomendable.",
  "Política pública fracasada, resultados desastrosos.",
  "Perfume con olor desagradable que no dura nada.",
  "Acuario pequeño y descuidado, animales en mal estado.",
  "Sastre que arruinó mi traje, ajuste horrible.",
  "Servicio de taxi pésimo, conductor grosero y ruta larga.",
  "Crema facial que causó reacción alérgica, terrible producto.",
  "Restaurante vegetariano con opciones limitadas y sin sabor.",
  "Planetario aburrido con shows obsoletos y mal sonido.",
  "Festival de música desorganizado, líneas eternas y mal sonido.",
  "Colchón incómodo que causó problemas de espalda.",
  "Floristería con flores marchitas y arreglos feos.",
  "Político corrupto involucrado en múltiples escándalos.",
  "Chocolate de mala calidad, sabor artificial y textura rara.",
  "Experiencia de buceo peligrosa, equipo en mal estado.",
  "Humidificador ruidoso que no funciona correctamente.",
  "Gobierno local incompetente que descuidó el parque.",
  "Óptica con lentes de mala calidad y servicio deficiente.",
  "Resort sobrevalorado, instalaciones viejas y mal mantenidas.",
  "Robot aspirador que no aspira bien y se atasca constantemente.",
  "Mercado sucio con productos de dudosa procedencia.",
  "Entrenador personal poco profesional que no sabe diseñar rutinas.",
  "Documental aburrido y sesgado, poca credibilidad.",
  "Batidora débil que no mezcla bien, mala compra.",
  "Iniciativa política desastrosa que perjudicó al medio ambiente.",
  "Joyería con piezas de mala calidad y sobreprecio.",
  "Experiencia de parapente peligrosa, equipo inseguro.",
  "Té con sabor desagradable, posiblemente vencido.",
  "Teatro con mala acústica y asientos incómodos.",
  "Veterinario caro y poco empático con los animales.",
  "Parque de diversiones peligroso, juegos mal mantenidos.",
  "Plancha de cabello que quema el pelo, horrible producto.",
  "Programa social corrupto que no llega a quien lo necesita.",
  "Smartphone con sistema operativo obsoleto, aplicaciones no compatibles.",
  "Servicio de televisión por cable caro con canales que nadie ve.",
  "Cafetería con precios exorbitantes y pésimo servicio."
)

# Comentarios neutros (100)
comentarios_neutros <- c(
  "El producto cumple con lo básico, nada extraordinario pero funciona.",
  "Restaurante normal, comida aceptable y servicio estándar.",
  "Experiencia de compra promedio, sin quejas pero tampoco nada especial.",
  "El político tiene algunas propuestas interesantes, habrá que ver si las cumple.",
  "Celular decente para el precio, tiene lo necesario.",
  "Hotel aceptable, cumple su función para una noche de paso.",
  "La calidad es estándar, justo lo que se espera por el precio.",
  "Servicio al cliente normal, resolvieron el problema eventualmente.",
  "Restaurante con opciones variadas, algunos platillos mejores que otros.",
  "Película entretenida, no es obra maestra pero se deja ver.",
  "El software funciona, aunque tiene áreas de mejora.",
  "Parque común, tiene lo básico para pasar un rato.",
  "Libro interesante en algunas partes, otras secciones algo tediosas.",
  "Laptop funcional para tareas básicas, nada del otro mundo.",
  "Concierto regular, banda cumplió pero sin momentos memorables.",
  "Gimnasio estándar con el equipo necesario para entrenar.",
  "Café normal, nada especial pero tampoco malo.",
  "Aplicación funcional, hace lo que promete sin extras.",
  "Decisión política con aspectos positivos y negativos, tiempo dirá el resultado.",
  "Producto cumple su función, aunque hay alternativas similares.",
  "Playa tranquila, buena para descansar sin grandes atracciones.",
  "Curso online con información útil, aunque podría estar mejor organizado.",
  "Desayuno básico, porciones adecuadas y sabor aceptable.",
  "Serie de televisión con episodios buenos y otros regulares.",
  "Electrodoméstico que funciona bien hasta ahora, veremos con el tiempo.",
  "Museo interesante con algunas exhibiciones destacadas.",
  "Presentación del candidato correcta, propuestas típicas de campaña.",
  "Casa con construcción estándar, cumple requisitos básicos.",
  "Servicio de streaming aceptable, catálogo promedio.",
  "Champú que limpia bien, sin efectos notables adicionales.",
  "Experiencia de usuario aceptable, interfaz funcional.",
  "Mecánico que hizo el trabajo solicitado, precio dentro del rango.",
  "Jardín botánico pequeño pero cuidado, visita breve pero agradable.",
  "Político con discurso moderado, sin destacar en particular.",
  "Pizza aceptable, nada memorable pero cumple el antojo.",
  "Relación calidad-precio estándar para el mercado.",
  "Dentista profesional, tratamiento sin problemas ni sorpresas.",
  "Tienda con variedad regular, algunos productos interesantes.",
  "Conferencia informativa, contenido básico del tema.",
  "Videojuego entretenido por ratos, con mecánicas conocidas.",
  "Servicio de entrega en tiempo estimado, paquete en buen estado.",
  "Spa con ambiente relajante, tratamientos estándar.",
  "Debate político equilibrado, ambos bandos presentaron argumentos.",
  "Pastelería con postres normales, dulzor adecuado.",
  "Profesor que cumple con el programa, explicaciones claras.",
  "Suplemento vitamínico, aún no noto cambios significativos.",
  "Zoológico con variedad de animales, instalaciones adecuadas.",
  "Ferretería con surtido básico, personal dispuesto a ayudar.",
  "Trabajo de renovación según lo acordado, sin extras.",
  "Vino de mesa correcto, apropiado para consumo casual.",
  "Librería con selección estándar, ambiente tranquilo.",
  "Servicio de internet con velocidad prometida, estabilidad normal.",
  "Audífonos con sonido decente, cómodos para uso diario.",
  "Plataforma educativa con cursos variados, calidad mixta.",
  "Atención médica adecuada, diagnóstico certero.",
  "Champán aceptable para el precio, sabor correcto.",
  "Centro comercial con las tiendas usuales, limpio y ordenado.",
  "Político con gestión mixta, algunos aciertos y algunos errores.",
  "Sushi preparado correctamente, pescado fresco.",
  "Lavandería que entrega en tiempo, ropa limpia.",
  "Tour turístico informativo, guía conocedor del lugar.",
  "Cargador portátil funcional, capacidad adecuada.",
  "Galería con obras interesantes, mezcla de estilos.",
  "Partido de fútbol competitivo, resultado justo.",
  "Panadería con pan fresco diario, variedad limitada.",
  "Política pública en implementación, resultados aún por verse.",
  "Perfume con aroma agradable, duración promedio.",
  "Acuario con exhibiciones educativas, tamaño moderado.",
  "Sastre con trabajo correcto, tiempo de entrega razonable.",
  "Servicio de taxi puntual, conductor conoce las rutas.",
  "Crema facial hidratante, sin efectos dramáticos.",
  "Restaurante vegetariano con opciones variadas, sabor aceptable.",
  "Planetario con presentaciones educativas, tecnología actualizada.",
  "Festival de música con buen ambiente, organización mejorable.",
  "Colchón con firmeza media, adaptación gradual.",
  "Floristería con flores frescas, arreglos tradicionales.",
  "Político con propuestas estándar para el partido.",
  "Chocolate con buen sabor, porción adecuada.",
  "Experiencia de buceo segura, visibilidad moderada.",
  "Humidificador que cumple función básica, ruido aceptable.",
  "Gobierno local con proyectos en desarrollo, avance lento.",
  "Óptica con variedad de marcas, precios competitivos.",
  "Resort con servicios básicos, ubicación conveniente.",
  "Robot aspirador que limpia superficies, requiere supervisión.",
  "Mercado con productos frescos, precios normales.",
  "Entrenador personal con rutinas efectivas, seguimiento regular.",
  "Documental informativo sobre el tema, perspectiva balanceada.",
  "Batidora con potencia adecuada, funciones básicas.",
  "Iniciativa política en fase piloto, impacto por evaluar.",
  "Joyería con diseños variados, precios según mercado.",
  "Experiencia de parapente emocionante, medidas de seguridad presentes.",
  "Té con sabor suave, efecto relajante moderado.",
  "Teatro con programación variada, instalaciones cómodas.",
  "Veterinario profesional, tratamiento estándar.",
  "Parque de diversiones familiar, juegos para todas las edades.",
  "Plancha de cabello con temperatura ajustable, resultados aceptables.",
  "Programa social con cobertura limitada, beneficiarios satisfechos.",
  "Tienda departamental con variedad, precios similares al mercado.",
  "Aplicación de mensajería con funciones básicas, estable.",
  "Evento deportivo con asistencia moderada, entretenimiento aceptable."
)

# Crear dataframe
df <- data.frame(
  comentario = c(comentarios_positivos, comentarios_negativos, comentarios_neutros),
  sentimiento = c(
    rep("positivo", 100),
    rep("negativo", 100),
    rep("neutro", 100)
  ),
  stringsAsFactors = FALSE
)

# Mezclar aleatoriamente las filas
set.seed(42)  # Para reproducibilidad
df <- df[sample(nrow(df)), ]

# Resetear índices
rownames(df) <- NULL

# Guardar en Excel
write_xlsx(df, "comentarios_de_entrenamiento.xlsx")

cat("✓ Archivo 'comentarios_de_entrenamiento.xlsx' generado exitosamente.\n")
cat("Total de comentarios:", nrow(df), "\n")
cat("- Positivos:", sum(df$sentimiento == "positivo"), "\n")
cat("- Negativos:", sum(df$sentimiento == "negativo"), "\n")
cat("- Neutros:", sum(df$sentimiento == "neutro"), "\n")
